version: '3'
services:
  php:
    container_name: php_1
    build: ./docker/php
    volumes:
      - './server:/var/www:cached'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'

  nginx:
    image: nginx
    container_name: nginx_1
    ports:
      - "0.0.0.0:8081:82"
    volumes:
      - './server:/var/www:cached'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
